### Fiona

In [17]:
import numpy as np
from scipy import linalg as la
from numpy.linalg import matrix_power
from scipy.sparse import dok_matrix
import pandas as pd

Problem 1

In [36]:
def p1(filename):
    nodes=[]
    with open(filename, 'r') as myfile:
        for line in myfile:
            try:
                line = list(map(int, line.strip().split()))
                nodes.append(line)
            except:
                pass
    N = np.amax(nodes) + 1
    A = np.zeros((N,N))
    for i in range (0,N):
        for j in range (0,N):
            if [i,j] in nodes:
                A[i,j]=1
    return A
        

In [45]:
p1('matrix.txt')

array([[0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.]])

Problem 2

In [43]:
def p2(A):
    m,n = A.shape
    A[A.sum(axis=1) == 0, :] = np.ones(n)
    D=A.sum(axis=1)
    K = A.T / D
    return(K)
    
    

In [44]:
p2(p1('matrix.txt'))

array([[0.        , 1.        , 0.125     , 0.33333333, 0.33333333,
        0.5       , 1.        , 1.        ],
       [0.        , 0.        , 0.125     , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.125     , 0.33333333, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.125     , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.125     , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.125     , 0.        , 0.33333333,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.125     , 0.33333333, 0.33333333,
        0.5       , 0.        , 0.        ],
       [1.        , 0.        , 0.125     , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

Problem 3

In [49]:
def p3(A,N=None,d=0.85,tol=1e-5):
    if N!=None:
        A=A[:N,:N]
    n=len(A)
    p_0 = np.random.rand(n)
    p_0= p_0/ np.sum(p_0)
    pdist = 100
    count=0
    while (pdist > tol) & (count < 1000):
        p_t = d * A @ p_0 + ((1 - d)/ n)
        pdist = la.norm(p_t - p_0)
        p_0 = p_t
        count += 1
    return(p_0)

    

In [51]:
p3(p2(p1('matrix.txt')))

array([0.43869573, 0.02171029, 0.02786154, 0.02171029, 0.02171029,
       0.02786154, 0.04585394, 0.3945964 ])

Problem 4

In [54]:
def p4(A,N=None,d=0.85):
    n = len(A)
    K = p2(A)
    E = np.ones((n, n))
    B = (d * K + ((1 - d) / n) * E)
    eigval, eigvec = la.eig(B)
    p_t = eigvec[:, 0]/ np.sum(eigvec[:,0])
    return p_t


In [55]:
p4(p2(p1('matrix.txt')))

array([0.03870928, 0.02641669, 0.48031139, 0.32401996, 0.04643401,
       0.03127529, 0.02641669, 0.02641669])

Problem 5

In [85]:
with open('ncaa2013.csv','r') as ncaafile:
    ncaafile.readline()
    winner=[]
    loser=[]
    for line in ncaafile:
        teams=line.strip().split(',')
        winner.append(teams[0])
        loser.append(teams[1])
names = np.unique(np.concatenate((winner, loser)))
n=len(names)
adj=np.zeros((n,n))
for i in range (0,len(winner)):
    name1, name2 = winner[i], loser[i]
    name1loc = np.where(name1 == names)
    name2loc = np.where(name2 == names)
    adj[name2loc, name1loc] = 1
A=p2(adj)
B=p3(A,d=0.7)
rank= np.argsort(B)
name_list= names[rank]
print(name_list[-5:][::-1])
        

['Duke' 'Butler' 'Louisville' 'Illinois' 'Indiana']
