## Problem Set 1
### Fiona Fan

#### Numpy
*1.*

In [1]:
import numpy as np
import pandas as pd

In [6]:
A=np.array([[3,-1,4],[1,5,-9]])
B=np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])
result = A@B
result

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

*2.*

In [11]:
A=np.array([[3,1,4],[1,5,9],[-5,3,1]])
result = -A@A@A+9*A@A-15*A
result

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

*3.*

In [31]:
def prob3():
    result1 = np.triu(np.ones((7,7)))
    result2 = np.tril(np.full((7,7),-1))
    iu1 = np.triu_indices(7,1)
    result2[iu1]=5
    return result1@result2@result1.astype(np.int64)
prob3()

array([[ -7.,  -8.,  -3.,   8.,  25.,  48.,  77.],
       [ -6., -12., -12.,  -6.,   6.,  24.,  48.],
       [ -5., -10., -15., -14.,  -7.,   6.,  25.],
       [ -4.,  -8., -12., -16., -14.,  -6.,   8.],
       [ -3.,  -6.,  -9., -12., -15., -12.,  -3.],
       [ -2.,  -4.,  -6.,  -8., -10., -12.,  -8.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.]])

*4.*

In [28]:
def neg0 (arr):
    arr1=arr.copy()
    arr1[arr<0]=0
    return arr1
neg0(result2)

array([[0, 5, 5, 5, 5, 5, 5],
       [0, 0, 5, 5, 5, 5, 5],
       [0, 0, 0, 5, 5, 5, 5],
       [0, 0, 0, 0, 5, 5, 5],
       [0, 0, 0, 0, 0, 5, 5],
       [0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0]])

*5.*

In [62]:
def prob5():
    A=np.arange(6).reshape((2,3))
    B=np.tril(np.ones((3,3)))*3
    C=np.eye(3)*3
    Z1 = np.zeros((3,3))
    Z2 = np.zeros((5,2))
    Z4 = np.zeros((2,3))
    I = np.eye(3)
    print(A.T.shape,A.shape, B.shape)
    col1=np.vstack((Z1,A,B))
    col2=np.vstack((A.T,Z2))
    col3=np.vstack((I,Z4,C))
    return np.hstack((col1,col2,col3))
# np.zeros((3,3))
prob5()


(3, 2) (2, 3) (3, 3)


array([[0., 0., 0., 0., 3., 1., 0., 0.],
       [0., 0., 0., 1., 4., 0., 1., 0.],
       [0., 0., 0., 2., 5., 0., 0., 1.],
       [0., 1., 2., 0., 0., 0., 0., 0.],
       [3., 4., 5., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 3., 0., 0.],
       [3., 3., 0., 0., 0., 0., 3., 0.],
       [3., 3., 3., 0., 0., 0., 0., 3.]])

*6.*

In [ ]:
import math

In [89]:
def row_stochastic(arr):
    arr1=arr.copy()
    sum1=arr1.sum(axis=1)
    return arr1/sum1[:,np.newaxis]
#     return arr1[(arr1.sum(axis=0)==1).reshape(-1,1),:]
row_stochastic(np.array([[2,1,1],[2,-1,0]]))

array([[ 0.5 ,  0.25,  0.25],
       [ 2.  , -1.  ,  0.  ]])

In [125]:
grid = np.load("grid.npy")
def prob7(g):
#     mask = np.eye(4)==1
#     temp = -1111
#     for i in np.arange(g.shape[0]-3):
#         for j in np.arange(g.shape[1]-3):
#             #rdiag
#             mat1 = np.diag(g[i:i+4,j:j+4])
#             #ldiag
#             mask=np.array([[False,False,False,True],[False,False,True,False],[False,True,False,False],[True,False,False,False]])
#             mat4 = g[i:i+4,j:j+4][mask]
#             #row
#             mat2 = g[i:i+4,j:j+4][0,:]
#             #col
#             mat3 = g[i:i+4,j:j+4][:,0]
# #             print (mat2)
#             prod1 = np.prod(mat1)
# #             print(prod1)
#             prod2 = np.prod(mat2)
#             prod3 = np.prod(mat3)
#             result = max(prod1,prod2,prod3,np.prod(mat4))
#             if result>temp:
#                 temp=result
    
    row=np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    col=np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    right_diag = np.max(grid[:-3,:-3]*grid[1:-2,1:-2]*grid[2:-1,2:-1]*grid[3:,3:])
    left_diag = np.max(grid[3:,:-3]*grid[2:-1,1:-2]*grid[1:-2,2:-1]*grid[:-3,3:])
    result= max(row,col,right_diag,left_diag)
    #check corner cases
    temp=result
    # checking corner cases
    for k in [-1,-2,-3]:
        mat1 = g[k,g.shape[0]-4:]
        mat2 = g[g.shape[0]-4:,k]
#         print(np.prod(mat1))
        if max(np.prod(mat1),np.prod(mat2))>temp:
            temp=result
    return temp
prob7(grid)
# np.product(np.diag(np.eye(3)*3))

70600674

### Standard Library
1.

In [1]:
def p1(L):
    return (min(L), max(L), sum(L)/len(L))

In [3]:
p1([1,2,3,4])

(1, 4, 2.5)

2.

In [11]:
objs = [1,"a",[1,2],(1,2),set([1,2]) ]
objs_2 = [2, "b", [2,3], (2,3), set([2,3])]

for i, ob in enumerate (objs):
    if ob == [1,2]:
        new = ob
        ob[1]=3
        print(f'{type(ob)}:{new==ob}' )
    else:
        new = ob
        new = objs_2[i]
        print(f'{type(ob)}:{new==ob}' )

    

<class 'int'>:False
<class 'str'>:False
<class 'list'>:True
<class 'tuple'>:False
<class 'set'>:False


3. 

In [19]:
import calculator as cal

def hyp(a,b):
    return cal.math.sqrt(cal.add(cal.prod(a,a),cal.prod(b,b)))
hyp(3,4)

5.0

4.

In [33]:
from itertools import combinations
test = list(range(3))
# list(combinations(test,len(test)))
def power_set(L):
    result=[]
    for i in range(len(L)+1):
        result.extend(combinations(L,i))
    return result
power_set(test)

[(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]

5.Please see `SDP4.py`

### OOP
1.

In [39]:
class Backpack:
    """A Backpack object class. Has a name, color, maximum size, and a list of contents.
    Attributes:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the maximum amount of items in the backpack.
        contents (list): the contents of the backpack.
    Functions:
        put(): Add an item to the backpack.
        take(): Remove and item from the backpack.
        dump(): Remove all the contents from the backpack.
    """
    
    def __init__(self, name, color, max_size=5):           # This function is the constructor.
        """Set the name, color, and max_size and initialize an empty list of contents.
        Parameters:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int): the maximum amount of items in the backpack.
        """
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []
    
    def put(self, item):
        """Check if there is room in the backpack. If there is,
        add 'item' to the backpack's list of contents. Else, tell the user that there is no room."""
        if len(self.contents) >= self.max_size:
            print("No Room!")
            return
        else:
            self.contents.append(item)  # Use 'self.contents', not just 'contents'.
        
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
        
    def dump(self):
        """Dump all of the contents from the backpack."""
        self.contents = []

In [40]:
def test_backpack():
    testpack = Backpack("Barry", "black")       # Instantiate the object.
    if testpack.name != "Barry":                # Test an attribute.
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)                      # Test a method.
    print("Contents:", testpack.contents)
    testpack.take("pencil")
    print("Contents:", testpack.contents)
    testpack.dump()
    print("Contents:", testpack.contents)

In [41]:
test_backpack()


Contents: ['pencil', 'pen', 'paper', 'computer']
Contents: ['pen', 'paper', 'computer']
Contents: []


2.

In [42]:
# Inherit from the Backpack class in the class definition.
class Jetpack(Backpack):
    """A Jetpack object class. Inherits from the Backpack class.
    A jetpack is a fueled backpack.
    Attributes:
        name (str): the name of the jetpack's owner.
        color (str): the color of the jetpack.
        max_size (int): the maximum amount of fuel that can fit inside.
        fuel_amount (int): how much fuel the with which the jetpack starts.
"""
    def __init__(self, name, color, max_size=2, fuel_amount=10):
        """Use the Backpack constructor to initialize the name, color,
        and max_size attributes. A knapsack only holds 3 item by default.
        Parameters:
            name (str): the name of the jetpack's owner.
            color (str): the color of the jetpack.
            max_size (int): the maximum amount of fuel that can fit inside.
            fuel_amount (int): how much fuel the with which the jetpack starts.
"""
        Backpack.__init__(self, name, color, max_size)
        self.fuel_amount = fuel_amount
        
    def put(self, item):
        """Check if there is room in the backpack. If there is,
        add 'item' to the backpack's list of contents. Else, tell the user that there is no room."""
        if len(self.contents) >= self.max_size:
            print("No Room!")
            return
        else:
            self.contents.append(item)  # Use 'self.contents', not just 'contents'.
        
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
        
    def fly(self, fuel_burned):
        """Check if there is enough fuel to burn. If so, burn the fuel. 
        Otherwise, let the user know there is not enough fuel."""
        if fuel_burned > self.fuel_amount:
            print("Not enough fuel!")
            return
        else:
            self.fuel_amount = fuel_burned
            
    def dump(self):
        """Dump all of the contents and fuel from the backpack."""
        self.fuel_amount = []
        self.contents = []

3.

In [43]:
class Backpack:
    """A Backpack object class. Has a name, color, maximum size, and a list of contents.
    Attributes:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the maximum amount of items in the backpack.
        contents (list): the contents of the backpack.
    Functions:
        put(): Add an item to the backpack.
        take(): Remove and item from the backpack.
        dump(): Remove all the contents from the backpack.
    """
    
    def __init__(self, name, color, max_size=5):           # This function is the constructor.
        """Set the name, color, and max_size and initialize an empty list of contents.
        Parameters:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int): the maximum amount of items in the backpack.
        """
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []
    
    def put(self, item):
        """Check if there is room in the backpack. If there is,
        add 'item' to the backpack's list of contents. Else, tell the user that there is no room."""
        if len(self.contents) >= self.max_size:
            print("No Room!")
            return
        else:
            self.contents.append(item)  # Use 'self.contents', not just 'contents'.
        
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
        
    def dump(self):
        """Dump all of the contents from the backpack."""
        self.contents = []
        
    def __add__(self, other):
        """Add the number of contents of each Backpack."""
        return len(self.contents) + len(other.contents)
    
    def __lt__(self, other):
        """If 'self' has fewer contents than 'other', return True.
        Otherwise, return False.
        """
        return len(self.contents) < len(other.contents)

    def __eq__(self, other):
        """If 'self' is the same as 'other', return True.
        Otherwise, return False.
        """
        return self.name == other.name and self.color == other.color and len(self.contents) == \
            len(other.contents)
    
    def __str__(self):
        """Construct a return a string representation for this backpack."""
        return "Owner:\t\t{} \nColor:\t\t{} \nSize:\t\t{} \nMax Size:\t{} \
            \nContents:\t{}".format(self.name, self.color, len(self.contents), self.max_size, self.contents)

In [46]:
pack1 = Backpack("Rose", "red")
pack2 = Backpack("Rose", "red")
print(pack1)
pack1==pack2

Owner:		Rose 
Color:		red 
Size:		0 
Max Size:	5             
Contents:	[]


True

4.

In [47]:
class ComplexNumber:
    
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag
        
    def conjugate(self):
        conj = ComplexNumber(self.real, -self.imag)
        return conj
    
    def __str__(self):
        if self.imag >= 0:
            s = "({}+{}j)".format(self.real, self.imag)
        else:
            s = "({}{}j)".format(self.real, self.imag)
        return s
            
    def __abs__(self):
        return (self.real**2 + self.imag ** 2) ** .5
    
    def __eq__(self, other):
        return self.real == other.real and self.imag == other.imag
    
    def __add__(self, other):
        new_real = self.real + other.real
        new_imag = self.imag + other.imag
        return ComplexNumber(new_real, new_imag)
        
    def __sub__(self, other):
        new_real = self.real - other.real
        new_imag = self.imag - other.imag
        return ComplexNumber(new_real, new_imag)
    
    def __mul__(self, other):
        new_real = self.real * other.real - self.imag * other.imag
        new_imag = self.real * other.imag + self.imag * other.real
        return ComplexNumber(new_real, new_imag)
        
    def __truediv__(self, other):
        t = self*other.conjugate()
        b = (other*other.conjugate()).real
        return ComplexNumber(t.real / b, t.imag/b)

In [48]:
def test_ComplexNumber(a, b):
    py_cnum, my_cnum = complex(a, b), ComplexNumber(a, b)
    # Validate the constructor.
    if my_cnum.real != a or my_cnum.imag != b:
        print("__init__() set self.real and self.imag incorrectly")
    # Validate conjugate() by checking the new number's imag attribute.
    if py_cnum.conjugate().imag != my_cnum.conjugate().imag:
        print("conjugate() failed for", py_cnum)
    # Validate __str__().
    if str(py_cnum) != str(my_cnum):
        print("__str__() failed for", py_cnum)
    if abs(py_cnum) != abs(my_cnum):
        print("__abs__() failed for", py_cnum)
    if my_cnum != my_cnum:
        print("__eq__() failed for", py_cnum)    
    if py_cnum + py_cnum != my_cnum + my_cnum:
        print("__add__() failed for", py_cnum)
    if py_cnum - py_cnum != my_cnum - my_cnum:
        print("__sub__() failed for", py_cnum)
    if py_cnum * py_cnum != my_cnum * my_cnum:
        print("__mul__() failed for", py_cnum)    
    if py_cnum / py_cnum != my_cnum / my_cnum:
        print("__truediv__() failed for", py_cnum)

In [49]:
test_ComplexNumber(3, -4)
test_ComplexNumber(2, 5)

### Exceptions and File I/O
1.

In [2]:
def arithmagic():
    step_1 = input("Enter a 3-digit number where the first and last "
                                           "digits differ by 2 or more: ")
    if len(step_1) != 3:
        raise ValueError("The first number is not a 3-digit number.")
    if abs(int(step_1[2])-int(step_1[0])) < 2:
        raise ValueError("The first number’s first and last digits differ by less than 2.")
    step_2 = input("Enter the reverse of the first number, obtained "
                                              "by reading it backwards: ")
    if int(step_2[2]) != int(step_1[0]) or int(step_2[0]) != int(step_1[2]) or int(step_2[1]) != int(step_1[1]):
        raise ValueError("The second number is not the reverse of the first number.")
    step_3 = input("Enter the positive difference of these numbers: ")
    if int(step_3) != abs(int(step_1)-int(step_2)):
        raise ValueError("The third number is not the positive difference of the first two numbers.")
    step_4 = input("Enter the reverse of the previous result: ")
    if int(step_4[2]) != int(step_3[0]) or int(step_4[0]) != int(step_3[2]) or int(step_4[1]) != int(step_3[1]):
        raise ValueError("The fourth number is not the reverse of the third number.")
    print(str(step_3), "+", str(step_4), "= 1089 (ta-da!)")

In [3]:
arithmagic()


Enter a 3-digit number where the first and last digits differ by 2 or more: 123
Enter the reverse of the first number, obtained by reading it backwards: 321
Enter the positive difference of these numbers: 198
Enter the reverse of the previous result: 891
198 + 891 = 1089 (ta-da!)


2.

In [55]:
from random import choice

def random_walk(max_iters=1e12):
    walk = 0
    directions = [1, -1]
    try:
        for i in range(int(max_iters)):
            walk += choice(directions)
    except KeyboardInterrupt:
        print("Process interrupted at iteration {}".format(i))
    else:
        print("Process completed")
    finally:
        return(walk)

In [56]:
print(random_walk())


Process interrupted at iteration 21012830
-9972


3.

In [4]:
class ContentFilter(object):
    def __init__(self, filename):
        self.filename = filename
        try:
            with open(self.filename,"r") as myfile:
                self.contents = myfile.read().split('\n')
        except FileNotFoundError:
            filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        except TypeError:
            filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        except OSError:
            filename = str(input("Please enter a valid file name:"))
            ContentFilter(filename)

In [5]:
cf1 = ContentFilter("cf_example.txt")


Please enter a valid file name:cf_example1.txt


4.

In [6]:
class ContentFilter(object):
    def __init__(self, filename):
        self.filename = filename
        try:
            with open(self.filename,"r") as myfile:
                self.contents = myfile.read().split('\n')
        except FileNotFoundError:
            filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        except TypeError:
            self.filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        except OSError:
            self.filename = input("Please enter a valid file name:")
            ContentFilter(filename)
        self.total = 0
        self.alpha = 0
        self.digit = 0
        self.whitespace = 0
        self.line = len(self.contents)
        for i in range(self.line):
            for j in range(len(self.contents[i])):
                self.total += 1
                if self.contents[i][j].isspace():
                    self.whitespace += 1
                if self.contents[i][j].isdigit():
                    self.digit += 1
                if self.contents[i][j].isalpha():
                    self.alpha += 1
            
            
    def uniform(self, new_filename, mode='w', case="upper"):
        if mode not in ['w','x','a']:
            raise ValueError("Mode is not 'w', 'x', or 'a'")
        if case not in ['upper','lower']:
            raise ValueError("Case is not 'upper' or 'lower'")
        with open(new_filename, mode) as newfile:
            for i in range(len(self.contents)):
                if case == "upper":
                    newfile.write(self.contents[i].upper() + "\n")
                elif case == "lower":
                    newfile.write(self.contents[i].lower() + "\n")
                    
    def reverse(self, new_filename, mode='w', unit ="line"):
        if mode not in ['w','x','a']:
            raise ValueError("Mode is not 'w', 'x', or 'a'")
        if unit not in ['line','word']:
            raise ValueError("Case is not 'line' or 'unit'")
        with open(new_filename, mode) as newfile:
                if unit == "word":
                    for i in range(len(self.contents)):
                        newfile.write(self.contents[i][::-1] + "\n")
                elif unit == "line":
                    for i in range(len(self.contents)):
                        newfile.write(self.contents[::-1][i] + "\n")
                        
    def transpose(self, new_filename, mode='w'):
        if mode not in ['w','x','a']:
            raise ValueError("Mode is not 'w', 'x', or 'a'")
        with open(new_filename, mode) as newfile:
            for i in range(len(self.contents[0].split())):
                new_line = []
                for j in range(len(self.contents)):
                    content = self.contents[j].split()
                    new_line.append(content[i])
                newfile.write(" ".join(new_line) + "\n")
    def __str__(self):
        return "Source file: {}".format(self.filename) + "\n" + "Total characters: {}".format(self.total) + "\n" + "Alphabetic characters: {}".format(self.alpha) \
                + "\n" + "Numerical characters: {}".format(self.digit) + "\n" + "Whitespace characters: {}".format(self.whitespace) + "\n" + "Number of lines: {}".format(self.line)

In [7]:
cf = ContentFilter("cf_example1.txt")


In [8]:
cf.uniform("uniform.txt", mode='a', case="lower")

In [9]:
cf.reverse("reverse.txt", mode='w', unit="word")
cf.reverse("reverse.txt", mode='a', unit="line")
cf.transpose("transpose.txt", mode='w')

In [10]:
print(cf)

Source file: cf_example1.txt
Total characters: 51933
Alphabetic characters: 29297
Numerical characters: 5294
Whitespace characters: 7742
Number of lines: 815


### Unit testing

Please see file solutions.py and test_solutions.py