## Problem Set 1
### Fiona Fan

#### Numpy
*1.*

In [1]:
import numpy as np
import pandas as pd

In [6]:
A=np.array([[3,-1,4],[1,5,-9]])
B=np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])
result = A@B
result

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

*2.*

In [11]:
A=np.array([[3,1,4],[1,5,9],[-5,3,1]])
result = -A@A@A+9*A@A-15*A
result

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

*3.*

In [31]:
def prob3():
    result1 = np.triu(np.ones((7,7)))
    result2 = np.tril(np.full((7,7),-1))
    iu1 = np.triu_indices(7,1)
    result2[iu1]=5
    return result1@result2@result1.astype(np.int64)
prob3()

array([[ -7.,  -8.,  -3.,   8.,  25.,  48.,  77.],
       [ -6., -12., -12.,  -6.,   6.,  24.,  48.],
       [ -5., -10., -15., -14.,  -7.,   6.,  25.],
       [ -4.,  -8., -12., -16., -14.,  -6.,   8.],
       [ -3.,  -6.,  -9., -12., -15., -12.,  -3.],
       [ -2.,  -4.,  -6.,  -8., -10., -12.,  -8.],
       [ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.]])

*4.*

In [28]:
def neg0 (arr):
    arr1=arr.copy()
    arr1[arr<0]=0
    return arr1
neg0(result2)

array([[0, 5, 5, 5, 5, 5, 5],
       [0, 0, 5, 5, 5, 5, 5],
       [0, 0, 0, 5, 5, 5, 5],
       [0, 0, 0, 0, 5, 5, 5],
       [0, 0, 0, 0, 0, 5, 5],
       [0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0]])

*5.*

In [62]:
def prob5():
    A=np.arange(6).reshape((2,3))
    B=np.tril(np.ones((3,3)))*3
    C=np.eye(3)*3
    Z1 = np.zeros((3,3))
    Z2 = np.zeros((5,2))
    Z4 = np.zeros((2,3))
    I = np.eye(3)
    print(A.T.shape,A.shape, B.shape)
    col1=np.vstack((Z1,A,B))
    col2=np.vstack((A.T,Z2))
    col3=np.vstack((I,Z4,C))
    return np.hstack((col1,col2,col3))
# np.zeros((3,3))
prob5()


(3, 2) (2, 3) (3, 3)


array([[0., 0., 0., 0., 3., 1., 0., 0.],
       [0., 0., 0., 1., 4., 0., 1., 0.],
       [0., 0., 0., 2., 5., 0., 0., 1.],
       [0., 1., 2., 0., 0., 0., 0., 0.],
       [3., 4., 5., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 3., 0., 0.],
       [3., 3., 0., 0., 0., 0., 3., 0.],
       [3., 3., 3., 0., 0., 0., 0., 3.]])

*6.*

In [ ]:
import math

In [89]:
def row_stochastic(arr):
    arr1=arr.copy()
    sum1=arr1.sum(axis=1)
    return arr1/sum1[:,np.newaxis]
#     return arr1[(arr1.sum(axis=0)==1).reshape(-1,1),:]
row_stochastic(np.array([[2,1,1],[2,-1,0]]))

array([[ 0.5 ,  0.25,  0.25],
       [ 2.  , -1.  ,  0.  ]])

In [125]:
grid = np.load("grid.npy")
def prob7(g):
#     mask = np.eye(4)==1
#     temp = -1111
#     for i in np.arange(g.shape[0]-3):
#         for j in np.arange(g.shape[1]-3):
#             #rdiag
#             mat1 = np.diag(g[i:i+4,j:j+4])
#             #ldiag
#             mask=np.array([[False,False,False,True],[False,False,True,False],[False,True,False,False],[True,False,False,False]])
#             mat4 = g[i:i+4,j:j+4][mask]
#             #row
#             mat2 = g[i:i+4,j:j+4][0,:]
#             #col
#             mat3 = g[i:i+4,j:j+4][:,0]
# #             print (mat2)
#             prod1 = np.prod(mat1)
# #             print(prod1)
#             prod2 = np.prod(mat2)
#             prod3 = np.prod(mat3)
#             result = max(prod1,prod2,prod3,np.prod(mat4))
#             if result>temp:
#                 temp=result
    
    row=np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    col=np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    right_diag = np.max(grid[:-3,:-3]*grid[1:-2,1:-2]*grid[2:-1,2:-1]*grid[3:,3:])
    left_diag = np.max(grid[3:,:-3]*grid[2:-1,1:-2]*grid[1:-2,2:-1]*grid[:-3,3:])
    result= max(row,col,right_diag,left_diag)
    #check corner cases
    temp=result
    # checking corner cases
    for k in [-1,-2,-3]:
        mat1 = g[k,g.shape[0]-4:]
        mat2 = g[g.shape[0]-4:,k]
#         print(np.prod(mat1))
        if max(np.prod(mat1),np.prod(mat2))>temp:
            temp=result
    return temp
prob7(grid)
# np.product(np.diag(np.eye(3)*3))

70600674

### Standard Library

#### Unit testing

*1.* The problem about the original function is that in case of 9, range(2,3) does not include the correct answer 3. Please see `sf.py` for the correct version

NameError: name 'py' is not defined